import streamlit as st
from pypdf import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="SnapCareer AI",
    page_icon="🚀",
    layout="wide"
)


# -----------------------------
# SKILLS DATABASE
# -----------------------------
SKILLS = [
    "python", "java", "javascript", "html", "css",
    "react", "node.js", "django", "flask",
    "sql", "mysql", "postgresql", "mongodb",
    "git", "github", "excel", "power bi", "tableau",
    "machine learning", "deep learning",
    "artificial intelligence", "data analysis",
    "data science", "numpy", "pandas",
    "scikit-learn", "tensorflow", "pytorch",
    "communication", "leadership", "teamwork"
]


# -----------------------------
# PDF TEXT EXTRACTION
# -----------------------------
def extract_pdf_text(uploaded_file):

    reader = PdfReader(uploaded_file)

    text = ""

    for page in reader.pages:

        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    return text


# -----------------------------
# SKILL EXTRACTION
# -----------------------------
def extract_skills(text):

    text = text.lower()

    found = []

    for skill in SKILLS:

        if skill in text:
            found.append(skill)

    return sorted(set(found))


# -----------------------------
# TEXT SIMILARITY
# -----------------------------
def calculate_similarity(resume, job):

    vectorizer = TfidfVectorizer(
        stop_words="english"
    )

    vectors = vectorizer.fit_transform(
        [resume, job]
    )

    score = cosine_similarity(
        vectors[0],
        vectors[1]
    )[0][0]

    return round(score * 100, 2)


# -----------------------------
# CAREER REPORT
# -----------------------------
def create_report(
    skill_match,
    text_similarity,
    matching_skills,
    missing_skills,
    roadmap,
    questions
):

    report = "SNAPCAREER AI - CAREER ANALYSIS REPORT\n"
    report += "=" * 55 + "\n\n"

    report += f"Skill Match: {skill_match}%\n"
    report += f"Text Similarity: {text_similarity}%\n\n"

    report += "MATCHING SKILLS\n"
    report += "-" * 30 + "\n"

    for skill in matching_skills:
        report += f"- {skill.title()}\n"

    report += "\nSKILL GAPS\n"
    report += "-" * 30 + "\n"

    for skill in missing_skills:
        report += f"- {skill.title()}\n"

    report += "\nLEARNING ROADMAP\n"
    report += "-" * 30 + "\n"

    for item in roadmap:
        report += f"- {item}\n"

    report += "\nINTERVIEW PREPARATION\n"
    report += "-" * 30 + "\n"

    for question in questions:
        report += f"- {question}\n"

    report += "\nGenerated by SnapCareer AI"

    return report


# -----------------------------
# HEADER
# -----------------------------
st.title("🚀 SnapCareer AI")

st.subheader("On-Device AI Career Assistant")

st.write(
    "Analyze your resume against a target job, "
    "identify skill gaps and generate an actionable career roadmap."
)

st.info(
    "🎯 Designed with Snapdragon-powered HP PCs "
    "as a target deployment environment."
)


# -----------------------------
# RESUME
# -----------------------------
st.markdown("## 📄 Your Resume")

input_method = st.radio(
    "Choose resume input:",
    ["Upload PDF", "Paste Resume"],
    horizontal=True
)

resume = ""

if input_method == "Upload PDF":

    uploaded_file = st.file_uploader(
        "Upload your resume PDF",
        type=["pdf"]
    )

    if uploaded_file:

        resume = extract_pdf_text(
            uploaded_file
        )

        st.success(
            "✅ Resume uploaded successfully."
        )

else:

    resume = st.text_area(
        "Paste your resume",
        height=250,
        placeholder="Paste your resume here..."
    )


# -----------------------------
# JOB DESCRIPTION
# -----------------------------
st.markdown("## 💼 Target Job")

job_description = st.text_area(
    "Paste the target job description",
    height=250,
    placeholder="Paste the job description here..."
)


# -----------------------------
# ANALYZE
# -----------------------------
if st.button(
    "🔍 Analyze Career Profile",
    use_container_width=True
):

    if not resume:

        st.warning(
            "Please upload or paste your resume."
        )

    elif not job_description:

        st.warning(
            "Please enter a job description."
        )

    else:

        # Extract skills
        resume_skills = extract_skills(resume)

        job_skills = extract_skills(
            job_description
        )


        # Matching skills
        matching_skills = [
            skill
            for skill in job_skills
            if skill in resume_skills
        ]


        # Missing skills
        missing_skills = [
            skill
            for skill in job_skills
            if skill not in resume_skills
        ]


        # -----------------------------
        # SKILL MATCH %
        # -----------------------------
        if len(job_skills) > 0:

            skill_match = round(
                len(matching_skills)
                / len(job_skills)
                * 100,
                2
            )

        else:

            skill_match = 0


        # -----------------------------
        # TEXT SIMILARITY
        # -----------------------------
        text_similarity = calculate_similarity(
            resume,
            job_description
        )


        # -----------------------------
        # CAREER ANALYSIS
        # -----------------------------
        st.markdown("---")

        st.header("📊 Career Analysis")


        # TOP METRICS
        col1, col2, col3 = st.columns(3)

        with col1:

            st.metric(
                "🎯 Skill Match",
                f"{skill_match}%"
            )

        with col2:

            st.metric(
                "🧠 Text Similarity",
                f"{text_similarity}%"
            )

        with col3:

            st.metric(
                "🔑 Skill Gaps",
                len(missing_skills)
            )


        st.caption(
            "Skill Match measures the proportion of detected "
            "job-required skills found in the resume. "
            "Text Similarity measures overall wording similarity."
        )


        # -----------------------------
        # SKILLS DASHBOARD
        # -----------------------------
        col1, col2 = st.columns(2)


        with col1:

            st.markdown(
                "### ✅ Matching Skills"
            )

            if matching_skills:

                for skill in matching_skills:

                    st.success(
                        skill.title()
                    )

            else:

                st.info(
                    "No matching skills detected."
                )


        with col2:

            st.markdown(
                "### ❌ Skill Gaps"
            )

            if missing_skills:

                for skill in missing_skills:

                    st.error(
                        skill.title()
                    )

            else:

                st.success(
                    "No major skill gaps detected."
                )


        # -----------------------------
        # ROADMAP
        # -----------------------------
        st.markdown("---")

        st.header(
            "📚 Personalized Career Roadmap"
        )

        roadmap = []

        for skill in missing_skills:

            roadmap.append(
                f"Learn {skill.title()} "
                "and build a small practical project."
            )


        if not roadmap:

            roadmap.append(
                "Strengthen your existing skills "
                "with advanced projects."
            )


        for index, item in enumerate(
            roadmap,
            start=1
        ):

            st.write(
                f"**Step {index}:** {item}"
            )


        # -----------------------------
        # RESUME SUGGESTIONS
        # -----------------------------
        st.markdown("---")

        st.header(
            "✍️ Resume Improvement Suggestions"
        )

        suggestions = [

            "Highlight skills that match the target role.",

            "Add measurable results to important projects.",

            "Mention relevant tools and technologies clearly.",

            "Keep project descriptions concise.",

            "Add GitHub or portfolio links where appropriate."

        ]


        for suggestion in suggestions:

            st.write(
                f"💡 {suggestion}"
            )


        # -----------------------------
        # INTERVIEW PREPARATION
        # -----------------------------
        st.markdown("---")

        st.header(
            "🎤 Interview Preparation"
        )

        questions = []

        for skill in matching_skills[:5]:

            questions.append(
                f"Explain your experience with "
                f"{skill.title()}."
            )


        questions.append(
            "Describe one project you have worked on."
        )

        questions.append(
            "What skill are you currently improving?"
        )


        for question in questions:

            st.write(
                f"❓ {question}"
            )


        # -----------------------------
        # DOWNLOAD REPORT
        # -----------------------------
        st.markdown("---")

        st.header(
            "📥 Career Report"
        )


        report = create_report(
            skill_match,
            text_similarity,
            matching_skills,
            missing_skills,
            roadmap,
            questions
        )


        st.download_button(
            "📥 Download Career Analysis Report",
            data=report,
            file_name="SnapCareer_AI_Report.txt",
            mime="text/plain",
            use_container_width=True
        )


        # -----------------------------
        # PRIVACY
        # -----------------------------
        st.markdown("---")

        st.caption(
            "🔐 Privacy-first concept: suitable AI workloads "
            "can be moved toward local/on-device inference "
            "on supported Snapdragon hardware."
        )


# -----------------------------
# FOOTER
# -----------------------------
st.markdown("---")

st.caption(
    "SnapCareer AI | Snapdragon® AI Lab Build & Present Challenge"
)
